### ISSUE TITLE
readthe docs documentation build failing

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#694]
## Current Behavior
Readthedocs fails during building the documentation.

## Expected Behavior
No fail.

## Minimum acceptance criteria
- [ ] No more fail.

## Failure Information (for bugs)
```
python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.2.6
initializing sphinxcontrib.datatemplates
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/bibliography.bib... parsed 12 entries
[autosummary] generating autosummary for: advanced-installation.rst, bibliography.rst, getting-started.rst, index.rst, reference/index.rst, tutorials/R-tutorial.md, tutorials/detecting-events.ipynb, tutorials/event-properties.ipynb, tutorials/heatmap.ipynb, tutorials/index.rst, tutorials/local-dataset.ipynb, tutorials/plot-main-sequence.ipynb, tutorials/preprocessing-raw-data.ipynb, tutorials/public-datasets.ipynb, tutorials/pymovements-in-10-minutes.ipynb, tutorials/saving-loading-events.ipynb, tutorials/saving-loading-preprocessed.ipynb
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.events.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.gaze.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.plotting.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.synthetic.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.DatasetDefinition.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.DatasetLibrary.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.DatasetPaths.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.GazeBase.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.GazeBaseVR.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.GazeGraph.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.GazeOnFaces.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.HBN.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.datasets.JuDo1000.rst, ..., /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.plotting.traceplot.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.plotting.tsplot.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.synthetic.step_function.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.archives.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.checks.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.decorators.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.downloads.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.filters.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.parsing.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.paths.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.__init__.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.apply.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.clear_events.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.compute_event_properties.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.compute_properties.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.detect.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.detect_events.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.download.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.extract.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.dataset.Dataset.load.rst, ..., /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.downloads.download_and_extract_archive.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.downloads.download_file.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.filters.events_split_nans.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.filters.filter_candidates_remove_nans.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.parsing.check_nan.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.parsing.compile_patterns.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.parsing.get_additional_columns.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.parsing.parse_eyelink.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.paths.get_filepaths.rst, /home/docs/checkouts/readthedocs.org/user_builds/pymovements/checkouts/latest/docs/source/reference/pymovements.utils.paths.match_filepaths.rst
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 17 source files that are out of date
updating environment: [new config] 160 added, 0 changed, 0 removed
[2Kreading sources... [  1%] advanced-installation
[2Kreading sources... [  1%] bibliography
[2Kreading sources... [  2%] getting-started
[2Kreading sources... [  2%] index
[2Kreading sources... [  3%] reference/index
[2Kreading sources... [  4%] reference/pymovements.dataset
[2Kreading sources... [  4%] reference/pymovements.dataset.Dataset
[2Kreading sources... [  5%] reference/pymovements.dataset.Dataset.__init__
[2Kreading sources... [  6%] reference/pymovements.dataset.Dataset.apply
[2Kreading sources... [  6%] reference/pymovements.dataset.Dataset.clear_events
[2Kreading sources... [  7%] reference/pymovements.dataset.Dataset.compute_event_properties
[2Kreading sources... [  8%] reference/pymovements.dataset.Dataset.compute_properties
[2Kreading sources... [  8%] reference/pymovements.dataset.Dataset.detect
[2Kreading sources... [  9%] reference/pymovements.dataset.Dataset.detect_events
[2Kreading sources... [  9%] reference/pymovements.dataset.Dataset.download
[2Kreading sources... [ 10%] reference/pymovements.dataset.Dataset.extract
[2Kreading sources... [ 11%] reference/pymovements.dataset.Dataset.load
[2Kreading sources... [ 11%] reference/pymovements.dataset.Dataset.load_event_files
[2Kreading sources... [ 12%] reference/pymovements.dataset.Dataset.load_gaze_files
[2Kreading sources... [ 12%] reference/pymovements.dataset.Dataset.pix2deg
[2Kreading sources... [ 13%] reference/pymovements.dataset.Dataset.pos2acc
[2Kreading sources... [ 14%] reference/pymovements.dataset.Dataset.pos2vel
[2Kreading sources... [ 14%] reference/pymovements.dataset.Dataset.save
[2Kreading sources... [ 15%] reference/pymovements.dataset.Dataset.save_events
[2Kreading sources... [ 16%] reference/pymovements.dataset.Dataset.save_preprocessed
[2Kreading sources... [ 16%] reference/pymovements.dataset.Dataset.scan
[2Kreading sources... [ 17%] reference/pymovements.dataset.DatasetDefinition
[2Kreading sources... [ 18%] reference/pymovements.dataset.DatasetDefinition.__init__
[2Kreading sources... [ 18%] reference/pymovements.dataset.DatasetLibrary
[2Kreading sources... [ 19%] reference/pymovements.dataset.DatasetLibrary.__init__
[2Kreading sources... [ 19%] reference/pymovements.dataset.DatasetLibrary.add
[2Kreading sources... [ 20%] reference/pymovements.dataset.DatasetLibrary.get
[2Kreading sources... [ 21%] reference/pymovements.dataset.DatasetPaths
[2Kreading sources... [ 21%] reference/pymovements.dataset.DatasetPaths.__init__
[2Kreading sources... [ 22%] reference/pymovements.dataset.DatasetPaths.fill_name
[2Kreading sources... [ 22%] reference/pymovements.dataset.DatasetPaths.get_preprocessed_filepath
[2Kreading sources... [ 23%] reference/pymovements.dataset.DatasetPaths.raw_to_event_filepath
[2Kreading sources... [ 24%] reference/pymovements.datasets
[2Kreading sources... [ 24%] reference/pymovements.datasets.GazeBase
[2Kreading sources... [ 25%] reference/pymovements.datasets.GazeBase.__init__
[2Kreading sources... [ 26%] reference/pymovements.datasets.GazeBaseVR
[2Kreading sources... [ 26%] reference/pymovements.datasets.GazeBaseVR.__init__
[2Kreading sources... [ 27%] reference/pymovements.datasets.GazeGraph
[2Kreading sources... [ 28%] reference/pymovements.datasets.GazeGraph.__init__
[2Kreading sources... [ 28%] reference/pymovements.datasets.GazeOnFaces
[2Kreading sources... [ 29%] reference/pymovements.datasets.GazeOnFaces.__init__
[2Kreading sources... [ 29%] reference/pymovements.datasets.HBN
[2Kreading sources... [ 30%] reference/pymovements.datasets.HBN.__init__
[2Kreading sources... [ 31%] reference/pymovements.datasets.JuDo1000
[2Kreading sources... [ 31%] reference/pymovements.datasets.JuDo1000.__init__
[2Kreading sources... [ 32%] reference/pymovements.datasets.PoTeC
[2Kreading sources... [ 32%] reference/pymovements.datasets.PoTeC.__init__
[2Kreading sources... [ 33%] reference/pymovements.datasets.SBSAT
[2Kreading sources... [ 34%] reference/pymovements.datasets.SBSAT.__init__
[2Kreading sources... [ 34%] reference/pymovements.datasets.ToyDataset
[2Kreading sources... [ 35%] reference/pymovements.datasets.ToyDataset.__init__
[2Kreading sources... [ 36%] reference/pymovements.datasets.ToyDatasetEyeLink
[2Kreading sources... [ 36%] reference/pymovements.datasets.ToyDatasetEyeLink.__init__
[2Kreading sources... [ 37%] reference/pymovements.events
[2Kreading sources... [ 38%] reference/pymovements.events.EventDataFrame
[2Kreading sources... [ 38%] reference/pymovements.events.EventDataFrame.__init__
[2Kreading sources... [ 39%] reference/pymovements.events.EventDataFrame.add_event_properties
[2Kreading sources... [ 39%] reference/pymovements.events.EventDataFrame.add_trial_column
[2Kreading sources... [ 40%] reference/pymovements.events.EventDataFrame.copy
[2Kreading sources... [ 41%] reference/pymovements.events.EventGazeProcessor
[2Kreading sources... [ 41%] reference/pymovements.events.EventProcessor
[2Kreading sources... [ 42%] reference/pymovements.events.amplitude
[2Kreading sources... [ 42%] reference/pymovements.events.dispersion
[2Kreading sources... [ 43%] reference/pymovements.events.disposition
[2Kreading sources... [ 44%] reference/pymovements.events.duration
[2Kreading sources... [ 44%] reference/pymovements.events.fill
[2Kreading sources... [ 45%] reference/pymovements.events.idt
[2Kreading sources... [ 46%] reference/pymovements.events.ivt
[2Kreading sources... [ 46%] reference/pymovements.events.location
[2Kreading sources... [ 47%] reference/pymovements.events.microsaccades
[2Kreading sources... [ 48%] reference/pymovements.events.peak_velocity
[2Kreading sources... [ 48%] reference/pymovements.gaze
[2Kreading sources... [ 49%] reference/pymovements.gaze.Experiment
[2Kreading sources... [ 49%] reference/pymovements.gaze.Experiment.__init__
[2Kreading sources... [ 50%] reference/pymovements.gaze.Experiment.pos2vel
[2Kreading sources... [ 51%] reference/pymovements.gaze.GazeDataFrame
[2Kreading sources... [ 51%] reference/pymovements.gaze.GazeDataFrame.__init__
[2Kreading sources... [ 52%] reference/pymovements.gaze.GazeDataFrame.apply
[2Kreading sources... [ 52%] reference/pymovements.gaze.GazeDataFrame.clone
[2Kreading sources... [ 53%] reference/pymovements.gaze.GazeDataFrame.detect
[2Kreading sources... [ 54%] reference/pymovements.gaze.GazeDataFrame.nest
[2Kreading sources... [ 54%] reference/pymovements.gaze.GazeDataFrame.pix2deg
[2Kreading sources... [ 55%] reference/pymovements.gaze.GazeDataFrame.pos2acc
[2Kreading sources... [ 56%] reference/pymovements.gaze.GazeDataFrame.pos2vel
[2Kreading sources... [ 56%] reference/pymovements.gaze.GazeDataFrame.smooth
[2Kreading sources... [ 57%] reference/pymovements.gaze.GazeDataFrame.transform
[2Kreading sources... [ 57%] reference/pymovements.gaze.GazeDataFrame.unnest
[2Kreading sources... [ 58%] reference/pymovements.gaze.Screen
[2Kreading sources... [ 59%] reference/pymovements.gaze.Screen.__init__
[2Kreading sources... [ 59%] reference/pymovements.gaze.Screen.pix2deg
[2Kreading sources... [ 60%] reference/pymovements.gaze.transforms.center_origin
[2Kreading sources... [ 61%] reference/pymovements.gaze.transforms.downsample
[2Kreading sources... [ 61%] reference/pymovements.gaze.transforms.norm
[2Kreading sources... [ 62%] reference/pymovements.gaze.transforms.pix2deg
[2Kreading sources... [ 62%] reference/pymovements.gaze.transforms.pos2acc
[2Kreading sources... [ 63%] reference/pymovements.gaze.transforms.pos2vel
[2Kreading sources... [ 64%] reference/pymovements.gaze.transforms.savitzky_golay
[2Kreading sources... [ 64%] reference/pymovements.gaze.transforms_numpy.consecutive
[2Kreading sources... [ 65%] reference/pymovements.gaze.transforms_numpy.downsample
[2Kreading sources... [ 66%] reference/pymovements.gaze.transforms_numpy.norm
[2Kreading sources... [ 66%] reference/pymovements.gaze.transforms_numpy.pix2deg
[2Kreading sources... [ 67%] reference/pymovements.gaze.transforms_numpy.pos2acc
[2Kreading sources... [ 68%] reference/pymovements.gaze.transforms_numpy.pos2vel
[2Kreading sources... [ 68%] reference/pymovements.gaze.transforms_numpy.split
[2Kreading sources... [ 69%] reference/pymovements.plotting
[2Kreading sources... [ 69%] reference/pymovements.plotting.heatmap
[2Kreading sources... [ 70%] reference/pymovements.plotting.main_sequence_plot
[2Kreading sources... [ 71%] reference/pymovements.plotting.traceplot
[2Kreading sources... [ 71%] reference/pymovements.plotting.tsplot
[2Kreading sources... [ 72%] reference/pymovements.synthetic
[2Kreading sources... [ 72%] reference/pymovements.synthetic.step_function
[2Kreading sources... [ 73%] reference/pymovements.utils
[2Kreading sources... [ 74%] reference/pymovements.utils.archives
[2Kreading sources... [ 74%] reference/pymovements.utils.archives.extract_archive
[2Kreading sources... [ 75%] reference/pymovements.utils.checks
[2Kreading sources... [ 76%] reference/pymovements.utils.checks.check_is_greater_than_zero
[2Kreading sources... [ 76%] reference/pymovements.utils.checks.check_is_int
[2Kreading sources... [ 77%] reference/pymovements.utils.checks.check_is_length_matching
[2Kreading sources... [ 78%] reference/pymovements.utils.checks.check_is_mutual_exclusive
[2Kreading sources... [ 78%] reference/pymovements.utils.checks.check_is_none_is_mutual
[2Kreading sources... [ 79%] reference/pymovements.utils.checks.check_is_not_none
[2Kreading sources... [ 79%] reference/pymovements.utils.checks.check_is_positive_value
[2Kreading sources... [ 80%] reference/pymovements.utils.checks.check_is_scalar
[2Kreading sources... [ 81%] reference/pymovements.utils.checks.check_nan_both_channels
[2Kreading sources... [ 81%] reference/pymovements.utils.checks.check_no_zeros
[2Kreading sources... [ 82%] reference/pymovements.utils.checks.check_shapes
[2Kreading sources... [ 82%] reference/pymovements.utils.checks.check_two_kwargs
[2Kreading sources... [ 83%] reference/pymovements.utils.decorators
[2Kreading sources... [ 84%] reference/pymovements.utils.decorators.auto_str
[2Kreading sources... [ 84%] reference/pymovements.utils.downloads
[2Kreading sources... [ 85%] reference/pymovements.utils.downloads.download_and_extract_archive
[2Kreading sources... [ 86%] reference/pymovements.utils.downloads.download_file
[2Kreading sources... [ 86%] reference/pymovements.utils.filters
[2Kreading sources... [ 87%] reference/pymovements.utils.filters.events_split_nans
[2Kreading sources... [ 88%] reference/pymovements.utils.filters.filter_candidates_remove_nans
[2Kreading sources... [ 88%] reference/pymovements.utils.parsing
[2Kreading sources... [ 89%] reference/pymovements.utils.parsing.check_nan
[2Kreading sources... [ 89%] reference/pymovements.utils.parsing.compile_patterns
[2Kreading sources... [ 90%] reference/pymovements.utils.parsing.get_additional_columns
[2Kreading sources... [ 91%] reference/pymovements.utils.parsing.parse_eyelink
[2Kreading sources... [ 91%] reference/pymovements.utils.paths
[2Kreading sources... [ 92%] reference/pymovements.utils.paths.get_filepaths
[2Kreading sources... [ 92%] reference/pymovements.utils.paths.match_filepaths
[2Kreading sources... [ 93%] tutorials/R-tutorial
[2Kreading sources... [ 94%] tutorials/detecting-events
/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (2.5).
Your version must be at least (2.14.2) but less than (4.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
[2Kreading sources... [ 94%] tutorials/event-properties
[2Kreading sources... [ 95%] tutorials/heatmap
[2Kreading sources... [ 96%] tutorials/index
[2Kreading sources... [ 96%] tutorials/local-dataset
[2Kreading sources... [ 97%] tutorials/plot-main-sequence
[2Kreading sources... [ 98%] tutorials/preprocessing-raw-data
[2Kreading sources... [ 98%] tutorials/public-datasets
[2Kreading sources... [ 99%] tutorials/pymovements-in-10-minutes

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbsphinx/__init__.py", line 618, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbsphinx/__init__.py", line 397, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 101, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 122, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/docs/.asdf/installs/python/3.9.18/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbclient/client.py", line 1009, in async_execute_cell
    raise DeadKernelError("Kernel died") from None
nbclient.exceptions.DeadKernelError: Kernel died

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbsphinx/__init__.py", line 627, in parse
    raise NotebookError(type(e).__name__ + ' in ' +
nbsphinx.NotebookError: DeadKernelError in tutorials/pymovements-in-10-minutes.ipynb:
Kernel died

Notebook error:
DeadKernelError in tutorials/pymovements-in-10-minutes.ipynb:
Kernel died
Command time: 421s Return: 2
```

The commit this started to appear is the following: [feat: trialize gaze.detect() (#655)](https://github.com/aeye-lab/pymovements/commit/95c1bf5a46727bb1141cb1d91e4d07894930229e)

As the kernel is also dying during calculating the event properties, I'm worried that my implementation caused a bug

**Comment by dkrako** [comment]
I think the problem is that we extend the reserved RAM usage at readthedocs, and #655 probably increased memory usage with the `partition_by()` call.

The strange thing is, that we only use the `ToyDataset` in the tutorial notebooks which doesn't have any groupby at all.
But then, probably there are trial columns added during dataset intialization so we get a single partition when calling `partition_by()` in that case. #631 could help us to make a step forward to add a way to disable adding the parsed filename level information to a `GazeDataFrame`.

The other strange thing is that this really is not a lot of data in the ToyDataset example..

**Comment by dkrako** [comment]
Maybe the issue is more in this part:

```
/home/docs/checkouts/readthedocs.org/user_builds/pymovements/envs/latest/lib/python3.9/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (2.5).
Your version must be at least (2.14.2) but less than (4.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
```

readthedocs has pandoc 2.5 installed here, and `nbconvert` expects 2.14, so that could be an issue.

**Comment by dkrako** [comment]
It's always the 10 minute tutorial when the kernel dies, let's try to find the cell(s) that lead to the dead kernel.
